### ISSUE TITLE
Validate email addresses

### ISSUE THREAD

**Issue by soph-g** [soph-g/peachio#4]
Check to make sure:
Email address is valid
Email address isn't already in the leads database
Make sure route returned on submission reflects these scenarios.

**Comment by beccapearce** [comment]
Email address is valid ✅
Email address isn't already in the leads database ✅

Routes redirect instead of just flashing on the current page- needs fix

**Comment by soph-g** [comment]
now fixed - using error messages to notify user of issues with email address. closing issue
